projects:
  cdk-14d-pet-api:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: us-east-2
        apiId: 7ox42djndfbovd7mq5lzfghhja
        maxDepth: 2
extensions:
  amplify:
    version: 3
